//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.1
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace timccexchg {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current")]
        public string OneMinVDCurrPath {
            get {
                return ((string)(this["OneMinVDCurrPath"]));
            }
            set {
                this["OneMinVDCurrPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\vd1min")]
        public string OneMinVDHistPath {
            get {
                return ((string)(this["OneMinVDHistPath"]));
            }
            set {
                this["OneMinVDHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current")]
        public string FiveMinVDCurrPath {
            get {
                return ((string)(this["FiveMinVDCurrPath"]));
            }
            set {
                this["FiveMinVDCurrPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\vd5min")]
        public string FiveMinVDHistPath {
            get {
                return ((string)(this["FiveMinVDHistPath"]));
            }
            set {
                this["FiveMinVDHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Database=TCS;UserID=db2inst1;Password=db2inst1;Server=10.21.50.31:50000")]
        public string dbConnectStr {
            get {
                return ((string)(this["dbConnectStr"]));
            }
            set {
                this["dbConnectStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current")]
        public string EpConfCurrPath {
            get {
                return ((string)(this["EpConfCurrPath"]));
            }
            set {
                this["EpConfCurrPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current")]
        public string SecDataCurrPath {
            get {
                return ((string)(this["SecDataCurrPath"]));
            }
            set {
                this["SecDataCurrPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\secdata")]
        public string SecDataHistPath {
            get {
                return ((string)(this["SecDataHistPath"]));
            }
            set {
                this["SecDataHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current")]
        public string CommCurrPath {
            get {
                return ((string)(this["CommCurrPath"]));
            }
            set {
                this["CommCurrPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\vd1hour")]
        public string OneHourVDHistPath {
            get {
                return ((string)(this["OneHourVDHistPath"]));
            }
            set {
                this["OneHourVDHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\vd1day")]
        public string OneDayVDHistPath {
            get {
                return ((string)(this["OneDayVDHistPath"]));
            }
            set {
                this["OneDayVDHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\rd5min")]
        public string FiveMinRDHistPath {
            get {
                return ((string)(this["FiveMinRDHistPath"]));
            }
            set {
                this["FiveMinRDHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\wd10min")]
        public string TenMinWDHistPath {
            get {
                return ((string)(this["TenMinWDHistPath"]));
            }
            set {
                this["TenMinWDHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\vi5min")]
        public string FiveMinVIHistPath {
            get {
                return ((string)(this["FiveMinVIHistPath"]));
            }
            set {
                this["FiveMinVIHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\aviplate1min")]
        public string OneMinAVIPlateHistPath {
            get {
                return ((string)(this["OneMinAVIPlateHistPath"]));
            }
            set {
                this["OneMinAVIPlateHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\avisec1min")]
        public string OneMinAVISectionHistPath {
            get {
                return ((string)(this["OneMinAVISectionHistPath"]));
            }
            set {
                this["OneMinAVISectionHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\vd_usable_rate_data_1day")]
        public string OneDayVDUnUseHistPath {
            get {
                return ((string)(this["OneDayVDUnUseHistPath"]));
            }
            set {
                this["OneDayVDUnUseHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\ramp_traffic_data_1day")]
        public string OneDayRampTrafficDataHistPath {
            get {
                return ((string)(this["OneDayRampTrafficDataHistPath"]));
            }
            set {
                this["OneDayRampTrafficDataHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\ramp_traffic_data_1hour")]
        public string OneHourRampTrafficDataHistPath {
            get {
                return ((string)(this["OneHourRampTrafficDataHistPath"]));
            }
            set {
                this["OneHourRampTrafficDataHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\secvd1min")]
        public string OneMinSectionVDHistPath {
            get {
                return ((string)(this["OneMinSectionVDHistPath"]));
            }
            set {
                this["OneMinSectionVDHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\miaoli\\vd1min")]
        public string OneMinVDMiaoLiHistPath {
            get {
                return ((string)(this["OneMinVDMiaoLiHistPath"]));
            }
            set {
                this["OneMinVDMiaoLiHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\miaoli\\sec1min")]
        public string OneMinSectionMiaoLiHistPath {
            get {
                return ((string)(this["OneMinSectionMiaoLiHistPath"]));
            }
            set {
                this["OneMinSectionMiaoLiHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\miaoli\\cms1min")]
        public string OneMinCMSMiaoLiHistPath {
            get {
                return ((string)(this["OneMinCMSMiaoLiHistPath"]));
            }
            set {
                this["OneMinCMSMiaoLiHistPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\current\\hist\\rsp_plan_data_1min")]
        public string OneMinRspPlanDataHistPath {
            get {
                return ((string)(this["OneMinRspPlanDataHistPath"]));
            }
            set {
                this["OneMinRspPlanDataHistPath"] = value;
            }
        }
    }
}
